var opening_hook = "charts/01_opening_hook.vg.json";
var seasonality_heatmap = "charts/02_seasonality_heatmap.vg.json";
var yearly_bars = "charts/03_yearly_bars.vg.json";
var state_small_multiples = "charts/04_state_small_multiples.vg.json";
var top_lgas_lollipop = "charts/05_top_lgas_lollipop.vg.json";
var drfa_categories = "charts/06_drfa_categories.vg.json";
var severity_state = "charts/07_severity_state.vg.json";
var dumbbell = "charts/08_dumbbell.vg.json";
var top_events = "charts/09_top_events.vg.json";
var cumulative_area = "charts/10_cumulative_area.vg.json";
var disaster_share = "charts/11_disaster_share.vg.json";
var event_scatter = "charts/12_event_scatter.vg.json";

vegaEmbed("#opening_hook", opening_hook, { "actions": false }).catch(console.error);
vegaEmbed("#seasonality_heatmap", seasonality_heatmap, { "actions": false }).catch(console.error);
vegaEmbed("#yearly_bars", yearly_bars, { "actions": false }).catch(console.error);
vegaEmbed("#state_small_multiples", state_small_multiples, { "actions": false }).catch(console.error);
vegaEmbed("#top_lgas_lollipop", top_lgas_lollipop, { "actions": false }).catch(console.error);
vegaEmbed("#drfa_categories", drfa_categories, { "actions": false }).catch(console.error);
vegaEmbed("#severity_state", severity_state, { "actions": false }).catch(console.error);
vegaEmbed("#dumbbell", dumbbell, { "actions": false }).catch(console.error);
vegaEmbed("#top_events", top_events, { "actions": false }).catch(console.error);
vegaEmbed("#cumulative_area", cumulative_area, { "actions": false }).catch(console.error);
vegaEmbed("#disaster_share", disaster_share, { "actions": false }).catch(console.error);
vegaEmbed("#event_scatter", event_scatter, { "actions": false }).catch(console.error);
